### ISSUE TITLE
The Choice : XAML or C#

### ISSUE THREAD

**Issue by martin-danhier** [Xaphok/GPlanner#21]
Hey,
With Xamarin, we have two different options for the design : XAML or C#.

 - **XAML** is clearer, you have a nice previewer to see the result of your code without having to deploy it, but IntelliSense is bugged and you'll often have to restart Visual Studio. Also, I think the code generated automatically isn't optimized. However, I think the community is bigger.

**Example :**
```<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Test.MainPage">
    <ContentPage.Content>
        <Frame>
            <Label Text="Hello world !"
                   VerticalOptions="Center"
                   HorizontalOptions="CenterAndExpand"
                   FontSize="30" />
        </Frame>
    </ContentPage.Content>
</ContentPage>
```

 - **C#** is a bit more complicated, but you have what you want. It's way less buggy. I think that you need to get used to it, then it's the same as XAML. However, with that option, we risk to have less contributors, and you haven't the live previewer (you have to deploy the app on the simulator / device)...

**Example:**
```
using Xamarin.Forms;

namespace Test
{
    public class MainPage : ContentPage
    {
        public MainPage()
        {
            Content = new Frame
            {
                Content = new Label
                {
                    Text = "Hello world !",
                    VerticalOptions = LayoutOptions.CenterAndExpand,
                    HorizontalOptions = LayoutOptions.CenterAndExpand,
                    FontSize = 30
                }
            };
        }
    }
}
```

So, we have to choice, and we need to decide before starting to code (and I'm beginning next week).
What do you think would be better ? XAML or C# ?

**Comment by comradelemoncake** [comment]
I'll fork this right now and contribute either way! I'm fairly proficient with both as well as AWS, Docker, and Azure. As for the choice, it really depends on the scope of the project. I personally like using C# because I think it's good to stay sharp with it, however if you only have a short time to get a interface going then I'd go with XAML. 

I will say the live previewer is nice though.

**Comment by martin-danhier** [comment]
After a lot of reflexion and some more experience in mobile application developpement, we'll develop this in Flutter (sorry). It is easy to learn, but most importantly, it works on Linux without a heavy IDE like Visual Studio Community.
