### ISSUE TITLE
Plan of the software + discussion

### ISSUE THREAD

**Issue by martin-danhier** [Xaphok/GPlanner#5]
We need to start somewhere. So, we have to set the plan of the software and everything will be simpler. (at least the basics). It works with Xamarin Forms, so the first thing would be to try the library in local to get used to it. Then, we'll be able to begin.

**Comment by martin-danhier** [comment]
So, the "administrative" work is nearly done : wiki's almost over, readme is complete etc...
We can start to focus on the app. First step, clone the repo in a test branch, try some things with xamarin to get used to it. (don't push ofc) When we'll know how all of that works, we'll start coding the real project.
(nb: i dont think we should label this as good first issue, a newcomer won't make the plan for us :D )

**Comment by ghost** [comment]
Yes but this is the first thing newcomers have to do: learn xamarin if needed and discuss to submit ideas
